<?php /** @var \Sebwite\ProductDownloads\Block\Product\Downloads $block */ ?>
<?php $downloads = $block->getDownloads(); ?>
<?php if( count($downloads) > 0 ) : ?>
    <div class="product-downloads s-wysiwyg">
        <ul>
            <?php foreach($downloads as $download) : ?>
                <li>
                    <a href="<?php echo $block->getDownloadUrl($download); ?>" target="_blank"><?php echo $download['download_file']; ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <!-- .product-downloads -->
<?php endif; ?>